import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Footer from "@/components/web/common/Footer";
import MobileFooter from "@/components/mobile/common/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="h-screen flex flex-col justify-between">
          <main className="bg-[#F8F9FA]">
            {children}
          </main>

          <div className="hidden lg:block">
            <Footer />
          </div>

          <div className="block lg:hidden">
            <MobileFooter />
          </div>
        </div>
      </body>
    </html>
  );
}
